data_path: data
model_dir: models
gcs_bucket: molecules_bucket

epochs: 100
batch_size: 32
learning_rate: 0.001
num_workers: 4

target_indices: [4]

train_ratio: 0.8
val_ratio: 0.1

patience: 10

profile: false
profiler_run_dir: "test_run"
