defaults:
  - model: gnn
  - training: standard
  - _self_

seed: 42

# Suppress Hydra outputs
hydra:
  run:
    dir: .
  output_subdir: null
  verbose: false
  job_logging:
    root:
      level: CRITICAL