name: Compare Best Model

on:
  repository_dispatch:
    types: [compare-best-model]

jobs:
  compare-and-promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          uv sync --dev --locked

      - name: Compare and promote model
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          WANDB_ENTITY: ${{ github.event.client_payload.entity_name }}
          NEW_MODEL_PATH: ${{ github.event.client_payload.entity_name }}/${{ github.event.client_payload.project_name }}/${{ github.event.client_payload.artifact_collection_name }}:${{ github.event.client_payload.artifact_version }}
        run: |
          echo "Comparing model: $NEW_MODEL_PATH"
          uv run python src/project_name/compare_promote.py
